/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coachingclassmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author yogesh
 */
public class DefaulterList extends javax.swing.JFrame {

    /**
     * Creates new form DefaulterList
     */
    Connection con=null;
       PreparedStatement pstmt=null;
       
        ResultSet rs=null;
    
    public DefaulterList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Start date :");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("End Date :");

        jDateChooser2.setDateFormatString("yyyy-MM-dd");
        jDateChooser2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Class :");

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class VI", "Class VII", "Class VIII", "Class IX", "Class X", "Class XI", "Class XII" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/demo?useSSL=false";
            String username="root";
            String password="YOGESH";
            con=DriverManager.getConnection(url,username,password);
            System.out.println("connection established");
            String val =jComboBox1.getSelectedItem().toString();
            String d1  = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
            String d2  = ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
            switch(val)
            {
                case "Class VI":
                    String sql="select a.student_id,s.first_name,s.last_name, count(l.subject_id) as total_lectures,\n" +
                               "sum(a.status) as lectures_present,(count(l.subject_id) - sum(a.status)) as lecture_absent\n" +
                               "from   attendance.classvi a join lectures1.class l  on a.lec_id = l.id\n" +
                               "join students.studentvi s on a.student_id = s.id\n" +
                               "where l.date between ? and ? group by a.student_id\n" +
                               "having (count(l.subject_id) - sum(a.status)) > count(l.subject_id)/2  ";
                     pstmt=con.prepareStatement(sql);
                    pstmt.setString(1, d1);
                    pstmt.setString(2, d2);
                    break;
                    
                case "Class VII":
                    String sql1="select a.student_id,s.first_name,s.last_name, count(l.subject_id) as total_lectures,\n" +
                               "sum(a.status) as lectures_present,(count(l.subject_id) - sum(a.status)) as lecture_absent\n" +
                               "from   attendance.classvii a join lectures1.class l  on a.lec_id = l.id\n" +
                               "join students.studentvii s on a.student_id = s.id\n" +
                               "where l.date between ? and ? group by a.student_id\n" +
                               "having (count(l.subject_id) - sum(a.status)) > count(l.subject_id)/2  ";
                     pstmt=con.prepareStatement(sql1);
                    pstmt.setString(1, d1);
                    pstmt.setString(2, d2);
                    break;
                    
                case "Class VIII":
                    String sql2="select a.student_id,s.first_name,s.last_name, count(l.subject_id) as total_lectures,\n" +
                               "sum(a.status) as lectures_present,(count(l.subject_id) - sum(a.status)) as lecture_absent\n" +
                               "from   attendance.classviii a join lectures1.class l  on a.lec_id = l.id\n" +
                               "join students.studentviii s on a.student_id = s.id\n" +
                               "where l.date between ? and ? group by a.student_id\n" +
                               "having (count(l.subject_id) - sum(a.status)) > count(l.subject_id)/2  ";
                     pstmt=con.prepareStatement(sql2);
                    pstmt.setString(1, d1);
                    pstmt.setString(2, d2);
                    break;
                    
                case "Class IX":
                    String sql3="select a.student_id,s.first_name,s.last_name, count(l.subject_id) as total_lectures,\n" +
                               "sum(a.status) as lectures_present,(count(l.subject_id) - sum(a.status)) as lecture_absent\n" +
                               "from   attendance.classix a join lectures1.class l  on a.lec_id = l.id\n" +
                               "join students.studentix s on a.student_id = s.id\n" +
                               "where l.date between ? and ? group by a.student_id\n" +
                               "having (count(l.subject_id) - sum(a.status)) > count(l.subject_id)/2  ";
                     pstmt=con.prepareStatement(sql3);
                    pstmt.setString(1, d1);
                    pstmt.setString(2, d2);
                    break;
                
                case "Class X":
                    String sql4="select a.student_id,s.first_name,s.last_name, count(l.subject_id) as total_lectures,\n" +
                               "sum(a.status) as lectures_present,(count(l.subject_id) - sum(a.status)) as lecture_absent\n" +
                               "from   attendance.classx a join lectures1.class l  on a.lec_id = l.id\n" +
                               "join students.studentx s on a.student_id = s.id\n" +
                               "where l.date between ? and ? group by a.student_id\n" +
                               "having (count(l.subject_id) - sum(a.status)) > count(l.subject_id)/2  ";
                     pstmt=con.prepareStatement(sql4);
                    pstmt.setString(1, d1);
                    pstmt.setString(2, d2);
                    break;
                    
                case "Class XI":
                    String sql5="select a.student_id,s.first_name,s.last_name, count(l.subject_id) as total_lectures,\n" +
                               "sum(a.status) as lectures_present,(count(l.subject_id) - sum(a.status)) as lecture_absent\n" +
                               "from   attendance.classxi a join lectures1.class l  on a.lec_id = l.id\n" +
                               "join students.studentxi s on a.student_id = s.id\n" +
                               "where l.date between ? and ? group by a.student_id\n" +
                               "having (count(l.subject_id) - sum(a.status)) > count(l.subject_id)/2  ";
                     pstmt=con.prepareStatement(sql5);
                    pstmt.setString(1, d1);
                    pstmt.setString(2, d2);
                    break;
                
                case "Class XII":
                    String sql6="select a.student_id,s.first_name,s.last_name, count(l.subject_id) as total_lectures,\n" +
                               "sum(a.status) as lectures_present,(count(l.subject_id) - sum(a.status)) as lecture_absent\n" +
                               "from   attendance.classxii a join lectures1.class l  on a.lec_id = l.id\n" +
                               "join students.studentxii s on a.student_id = s.id\n" +
                               "where l.date between ? and ? group by a.student_id\n" +
                               "having (count(l.subject_id) - sum(a.status)) > count(l.subject_id)/2  ";
                     pstmt=con.prepareStatement(sql6);
                    pstmt.setString(1, d1);
                    pstmt.setString(2, d2);
                    break;
                    
            }
            rs=pstmt.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
             
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DefaulterList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DefaulterList.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        try {
            pstmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(DefaulterList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(DefaulterList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DefaulterList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DefaulterList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DefaulterList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DefaulterList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DefaulterList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
