/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coachingclassmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author yogesh
 */
public class MonthlyScheduled extends javax.swing.JPanel {

    /**
     * Creates new form MonthlyScheduled
     */
    Connection con=null;
        Statement stmt=null;
        ResultSet rs=null;
               PreparedStatement pstmt=null;

    public MonthlyScheduled() {
                    initComponents();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/demo?useSSL=false";
            String username="root";
            String password="YOGESH";
            con=DriverManager.getConnection(url,username,password);
            System.out.println("connection established");
            jComboBox1.removeAllItems();
            String sql ="select first_name,last_name from teacher1.teacher_info";
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            while(rs.next())
            {
                jComboBox1.addItem(rs.getString("first_name")+" "+rs.getString("last_name"));
            }
           
                             
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MonthlyScheduled.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MonthlyScheduled.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        try {
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(MonthlyScheduled.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(MonthlyScheduled.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        jRadioButton1.setText("jRadioButton1");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lecturer's Name");

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Date");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jDateChooser2.setDateFormatString("yyyy-MM-dd");
        jDateChooser2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Class");

        jComboBox2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Class VI", "Class VII", "Class VIII", "Class IX", "Class X", "Class XI", "Class XII" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/demo?useSSL=false";
            String username="root";
            String password="YOGESH";
            con=DriverManager.getConnection(url,username,password);
            System.out.println("connection established");
            String d1  = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
            String d2  = ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
             System.out.println("the date for montly scheduled is "+d1+" "+d2);
                                
            String t = jComboBox1.getSelectedItem().toString();
            System.out.println("connection established");
            String val=jComboBox2.getSelectedItem().toString();
            switch(val){
                
                case "Class VI":
                    String sql1="select l.date,s.subject_name,t.first_name,t.last_name\n" +
"from lectures1.class l join subjects1.classvi s\n" +
"on l.subject_id = s.id\n" +
"join teacher1.teacher_info t \n" +
"on l.teacher_id=t.id\n" +
"where l.date between \""+d1+"\" and \""+d2+"\" and\n" +
"concat(t.first_name,' ',t.last_name)=\""+t+"\" and class=\"Class VI\"";
          pstmt=con.prepareStatement(sql1);
            break;
                  
                case "Class VII":
                    String sql2="select l.date,s.subject_name,t.first_name,t.last_name\n" +
"from lectures1.class l join subjects1.classvii s\n" +
"on l.subject_id = s.id\n" +
"join teacher1.teacher_info t \n" +
"on l.teacher_id=t.id\n" +
"where l.date between \""+d1+"\" and \""+d2+"\" and\n" +
"concat(t.first_name,' ',t.last_name)=\""+t+"\" and class=\"Class VII\"";
          pstmt=con.prepareStatement(sql2);
            break;
            
                case "Class VIII":
                    String sql3="select l.date,s.subject_name,t.first_name,t.last_name\n" +
"from lectures1.class l join subjects1.classviii s\n" +
"on l.subject_id = s.id\n" +
"join teacher1.teacher_info t \n" +
"on l.teacher_id=t.id\n" +
"where l.date between \""+d1+"\" and \""+d2+"\" and\n" +
"concat(t.first_name,' ',t.last_name)=\""+t+"\" and class=\"Class VIII\"";
          pstmt=con.prepareStatement(sql3);
            break;
            
                case "Class IX":
                    String sql4="select l.date,s.subject_name,t.first_name,t.last_name\n" +
"from lectures1.class l join subjects1.classix s\n" +
"on l.subject_id = s.id\n" +
"join teacher1.teacher_info t \n" +
"on l.teacher_id=t.id\n" +
"where l.date between \""+d1+"\" and \""+d2+"\" and\n" +
"concat(t.first_name,' ',t.last_name)=\""+t+"\" and class=\"Class IX\"";
          pstmt=con.prepareStatement(sql4);
            break;
                case "Class X":
                    String sql5="select l.date,l.class,s.subject_name,t.first_name,t.last_name\n" +
"from lectures1.class l join subjects1.classx s\n" +
"on l.subject_id = s.id\n" +
"join teacher1.teacher_info t \n" +
"on l.teacher_id=t.id\n" +
"where l.date between \""+d1+"\" and \""+d2+"\" and\n" +
"concat(t.first_name,' ',t.last_name)=\""+t+"\" and class=\"Class X\"";
          pstmt=con.prepareStatement(sql5);
            break;
            
                case "Class XI":
                    String sql6="select l.date,s.subject_name,t.first_name,t.last_name\n" +
"from lectures1.class l join subjects1.classxi s\n" +
"on l.subject_id = s.id\n" +
"join teacher1.teacher_info t \n" +
"on l.teacher_id=t.id\n" +
"where l.date between \""+d1+"\" and \""+d2+"\" and\n" +
"concat(t.first_name,' ',t.last_name)=\""+t+"\" and class=\"Class XI\"";
          pstmt=con.prepareStatement(sql6);
            break;
            
                case "Class XII":
                    String sql7="select l.date,s.subject_name,t.first_name,t.last_name\n" +
"from lectures1.class l join subjects1.classxii s\n" +
"on l.subject_id = s.id\n" +
"join teacher1.teacher_info t \n" +
"on l.teacher_id=t.id\n" +
"where l.date between \""+d1+"\" and \""+d2+"\" and\n" +
"concat(t.first_name,' ',t.last_name)=\""+t+"\" and class=\"Class XII\"";
          pstmt=con.prepareStatement(sql7);
            break;
            }
            
            
            
            rs=pstmt.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MonthlyScheduled.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MonthlyScheduled.class.getName()).log(Level.SEVERE, null, ex);
        }
          
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
